SMS/urls.py
from django.urls import path

from . import views

app_name = 'SMS'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='About'),
    path('student/<int:student_id>/', views.student, name = 'student'),
    path('articles/', views.articles, name = 'Articles'),
    path('contact_us/', views.contact_us, name = 'Contact_Us'),
    path('sitemaps/', views.site_map, name = 'Sitemaps'),
    path('login/', views.login , name = 'Login'),
    path('student/<int:student_id>/timetable/', views.view_student_timetable, name ='ViewTimeTableSudent'),
    path('student/<int:student_id>/AcademicDetail/', views.view_student_academic_detail, name = 'StudentAcademicDetail'),
    path('student/<int:student_id>/ViewDateSheet/' , views.view_date_sheet ,name = 'ViewDateSheet'),
    path('student/<int:student_id>/ViewResult/' , views.view_result ,name = 'ViewResult'),
    path('student/<int:student_id>/SendStudentRequest/' , views.send_student_request ,name = 'SendStudentRequest'),
    path('student/<int:student_id>/UploadStudentAssignment/' , views.upload_student_assignment ,name = 'UploadStudentAssignment'),
    path('student/<int:student_id>/ViewStudentFee/' , views.view_student_fee ,name = 'ViewStudentFee'),

    path('teacher/<int:teacher_id>/', views.teacher_dashboard, name = 'Teacher'),
    path('teacher/<int:teacher_id>/timetabe/', views.teacher_timetable, name = 'TeacherTimeTable'),
    path('teacher/<int:teacher_id>/assignments/', views.teacher_upload_assignments, name = 'TeacherAssignments'),
    path('teacher/<int:teacher_id>/attendance/', views.teacher_attendance, name = 'TeacherAttendance'),
    path('teacher/<int:teacher_id>/payroll/', views.teacher_payroll, name = 'TeacherPayroll'),
    path('teacher/<int:teacher_id>/request/', views.teacher_request, name = 'TeacherRequest'),
    path('teacher/<int:teacher_id>/result/', views.teacher_result, name = 'TeacherResult'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SMS.urls'))
]

SMS/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render,redirect
from django.http import HttpResponseRedirect
from .models import Person,Student
from django.http import HttpResponse
from django.views.generic import View
from django.template.loader import get_template
from .utils import render_to_pdf
from .models import Teacher, Login, Request, Studentsection, Fee
from django.db import connection


# Create your views here.

def index(request):
        
        return render(request, 'SMS/index.html')

def articles(request):
    return render(request, 'SMS/articles.html')

def contact_us(request):
    return render(request, 'SMS/contact-us.html')

def site_map(request):
    return render(request, 'SMS/sitemap.html')

def about(request):
    return render(request, 'SMS/about-us.html')

def login(request):
        incorrect_password = "False"
        if request.method == 'POST':
                print ("logged")
                name = request.POST.get('inputEmail')
                password = request.POST.get('inputPassword')
                print (name)
                print (password)
                if name == "admin@a.com" and password == "1234":
                        return redirect('/admin/')
                else :
                        try :   
                                current_user = Login.objects.get(username = name, password = password)
                                print(current_user.username)
                                if current_user.role == 'Student':
                                        return redirect('/sms/student/' + str(current_user.personid.id) )
                                elif current_user.role == 'Teacher':
                                        return redirect('/sms/teacher/' + str(current_user.personid.id))
                                else:
                                        return redirect('/admin/')
                        except:
                                incorrect_password = "False"
                                return render(request,'sms/login.html', {'incorrectPassword' :incorrect_password})
                
        else:
                return render(request,'sms/login.html', {'incorrectPassword' :incorrect_password})  
        

def view_student_timetable(request,student_id):
    return render(request, 'SMS/TimeTable.html', {'StudentId' : student_id})

def view_student_academic_detail(request, student_id):
        curr_Person = Person.objects.get(id = student_id)
        Name = curr_Person.firstname + " " + curr_Person.lastname
        Email = curr_Person.email
        Contact = curr_Person.contact
        DOB = curr_Person.dateofbirth.strftime('%m/%d/%Y')
        Gender = curr_Person.gender
        if Gender == 1:
                Gender = "Male"
        else :
                Gender = "Female"
                
        curr_Student = Student.objects.get(id = curr_Person)
        RegNo = curr_Student.registrationno
        try : 
                curr_StudentSection = Studentsection.objects.get(studentid = student_id)
                SectionOfStudent = curr_StudentSection.sectionid.name
        except:
                SectionOfStudent = "N/A"
        try:
                TeacherOfStudent = curr_StudentSection.sectionid.teacherid.id.firstname + " " + curr_StudentSection.sectionid.teacherid.id.lastname
        except:
                TeacherOfStudent = "N/A"
        try:
                ClassOfStudent = curr_StudentSection.sectionid.classid.name
                
        except:
              ClassOfStudent = "N/A"
        return render(request, 'SMS/AcademicDetail.html', {'StudentId' : student_id, 'RegNo': RegNo, 'Name' : Name , 'Email' : Email , 'Contact': Contact, 'DOB': DOB, 'Gender': Gender, 'SectionOfStudent' : SectionOfStudent, 'TeacherOfStudent': TeacherOfStudent, 'ClassOfStudent' : ClassOfStudent})

def student(request, student_id):
        curr_Person = Person.objects.get(id = student_id)
        Name = curr_Person.firstname + " " + curr_Person.lastname
        Email = curr_Person.email
        Contact = curr_Person.contact
        DOB = curr_Person.dateofbirth.strftime('%m/%d/%Y')
        Gender = curr_Person.gender
        if Gender == 1:
                Gender = "Male"
        else :
                Gender = "Female"
                
        curr_Student = Student.objects.get(id = curr_Person)
        RegNo = curr_Student.registrationno
        try : 
                curr_StudentSection = Studentsection.objects.get(studentid = student_id)
                SectionOfStudent = curr_StudentSection.sectionid.name
        except:
                SectionOfStudent = "N/A"
        try:
                TeacherOfStudent = curr_StudentSection.sectionid.teacherid.id.firstname + " " + curr_StudentSection.sectionid.teacherid.id.lastname
        except:
                TeacherOfStudent = "N/A"
        try:
                ClassOfStudent = curr_StudentSection.sectionid.classid.name
                
        except:
              ClassOfStudent = "N/A"
        return render(request, 'SMS/AcademicDetail.html', {'StudentId' : student_id, 'RegNo': RegNo, 'Name' : Name , 'Email' : Email , 'Contact': Contact, 'DOB': DOB, 'Gender': Gender, 'SectionOfStudent' : SectionOfStudent, 'TeacherOfStudent': TeacherOfStudent, 'ClassOfStudent' : ClassOfStudent})

def view_date_sheet(request, student_id):
        cursor = connection.cursor()
        result_set = ""
        try:
                cursor.execute('EXEC prDateSheetio @Id ='+ str(student_id) )
                result_set = cursor.fetchall()
        finally:
                cursor.close()  
        print (result_set)
        return render(request, 'SMS/DateSheet.html', {'StudentId' : student_id, 'result' : result_set})

def view_result(request,student_id):
        cursor = connection.cursor()
        result_set = ""
        try:
                cursor.execute('EXEC prStudentResult @Id ='+ str(student_id) )
                result_set = cursor.fetchall()
        finally:
                cursor.close()  
        print (result_set)
        return render(request, 'SMS/Result.html', {'StudentId' : student_id, 'result' : result_set})

def send_student_request(request, student_id):
        if request.method == 'POST':
                Student = Person.objects.get(id = student_id)
                description = request.POST.get('Description')
                if description == None :
                        description = "N/A"
                new_request = Request(personid = Student, description = description)
                new_request.save()
                return render(request, 'SMS/Request.html', {'StudentId' : student_id})
        else:
                return render(request, 'SMS/Request.html', {'StudentId' : student_id})

def upload_student_assignment(request,student_id):
    return render(request, 'SMS/Assignments.html', {'StudentId' : student_id})

def view_student_fee(request, student_id):
        curr_Section = Studentsection.objects.get(studentid = student_id)
        student_class = curr_Section.classid.name
        student_fee = Fee.objects.filter(classid = curr_Section.classid.id).first()
        fee_month = student_fee.month
        challan_id = student_fee.challanid
        due_date = student_fee.duedate.strftime('%m/%d/%Y')
        amount = student_fee.amount

        return render(request, 'SMS/Fee.html', {'StudentId' : student_id, 'Class': student_class, 'Month' : fee_month, 'Id' : challan_id, 'Duedate' : due_date , 'Amount' : amount})


def teacher_dashboard(request,teacher_id):
        
        curr_Person = Person.objects.get(id = teacher_id)
        Name = curr_Person.firstname + " " + curr_Person.lastname
        Email = curr_Person.email
        Contact = curr_Person.contact
        DOB = curr_Person.dateofbirth.strftime('%m/%d/%Y')
        Gender = curr_Person.gender
        if Gender == 1:
                Gender = "Male"
        else :
                Gender = "Female"
        
        curr_Teacher = Teacher.objects.get(id = curr_Person)
        Designation = curr_Teacher.designation
        
        return render(request, 'SMS/indexT.html', {'TeacherId' : teacher_id, 'Name' : Name , 'Email' : Email , 'Contact': Contact, 'DOB': DOB, 'Gender': Gender, 'Designation' : Designation})


def teacher_upload_assignments(request, teacher_id):
        return render(request, 'SMS/AssignmentsT.html', {'TeacherId' : teacher_id})


def teacher_attendance(request,teacher_id):
        return render(request, 'SMS/AttendanceT.html', {'TeacherId' : teacher_id})


def teacher_payroll(request,teacher_id):
        return render(request, 'SMS/payroll.html', {'TeacherId' : teacher_id})


def teacher_request(request,teacher_id):
        if request.method == 'POST':
                description = request.POST.get('Description')
                new_request = Request(personid = 1, description = description)
                new_request.save()
                return render(request, 'SMS/teacher', {'TeacherId' : teacher_id})


        else:
                return render(request, 'SMS/RequestT.html', {'TeacherId' : teacher_id})
        
def teacher_timetable(request,teacher_id):
        return render(request, 'SMS/TimetableT.html', {'TeacherId' : teacher_id})

def teacher_result(request,teacher_id):
        return render(request, 'SMS/ResultT.html', {'TeacherId' : teacher_id})

SMS/templates/SMS/AdminRegister.html
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
  <div class="container">
    <aside>
      <h3>Categories</h3>
      <ul class="categories">
        
        <li><span><a href="{% url 'SMS:Login' %}">Student</a></span></li>
        <li><span><a href="{% url 'SMS:Login' %}">Teacher</a></span></li>
        
      </ul>
     
  </div>
  {% endblock %}

SMS/templates/SMS/Assignments.html
<title>Student's Site | Student Home</title>
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
<aside>
    <h3>Categories</h3>
    <ul class="categories">
        <li><a href= "{% url 'SMS:ViewTimeTableSudent' StudentId %}" class="m1">Time Table</a></li>
        <li><a href= "{% url 'SMS:ViewDateSheet' StudentId %}" class="m2">Date Sheet</a></li>
        <li><a href= "{% url 'SMS:ViewResult' StudentId %}" class="m3">Result</a></li>
        <li><a href= "{% url 'SMS:SendStudentRequest' StudentId %}" class="m4">Request</a></li>
        <li><a href= "{% url 'SMS:UploadStudentAssignment' StudentId %}" class="m5">Assignments</a></li>
        <li><a href= "{% url 'SMS:StudentAcademicDetail' StudentId %}" class="m6">Academic Detail</a></li>
        <li><a href= "{% url 'SMS:ViewStudentFee'  StudentId%}" class="m7">Fee</a></li>
    </ul>
    </aside>
    <section id="content">
    <div class="inside">
      <h2>Assignments <span>Detail</span></h2>

      <form id="contacts-form" action="#">
        <fieldset>
            <label>choose File:</label>
            <input type="file" on/>
            
          <button type="button"  align = "centre">SUBMIT</button>
          
      </fieldset>
      </form>
      </div>
      </section>
      
      
    </div>
 {% endblock %}

SMS/templates/SMS/AssignmentsT.html
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
<aside>
    <h3>Categories</h3>
    <ul class="categories">
        <li class="current"><a href="{% url 'SMS:Teacher' TeacherId %}" class="m1">Details</a></li>
                      <li><a href="{% url 'SMS:TeacherTimeTable' TeacherId %}" class="m2">Time TimeTable</a></li>
                      <li><a href="{% url 'SMS:TeacherResult' TeacherId %}" class="m3">Result</a></li>
                      <li><a href="{% url 'SMS:TeacherRequest' TeacherId %}" class="m4">Request</a></li>
                      <li><a href="{% url 'SMS:TeacherAssignments' TeacherId %}" class="m5">Assignments</a></li>
                     
                      <li><a href="{% url 'SMS:TeacherPayroll' TeacherId %}" class="m7">Payroll</a></li>
                      <li><a href="{% url 'SMS:TeacherAttendance' TeacherId %}" class="m8">Attendance</a></li>
                   
    </ul>
    </aside>
    <section id="content">
    <div class="inside">
        <h2>Assignments <span>Detail</span></h2>
<form id="contacts-form" action="#">
  <fieldset>
    <div class="field">
      <label>choose File:</label>
      <input type="text" value="" style="width:134px"/>
    </div>

    <button type="button"  align = "centre">Upload</button>
    <button type="button"  align = "centre">Back</button>
    
</fieldset>
</form>
      </div>
      </section>
      
      
    </div>
 {% endblock %}

SMS/templates/SMS/AttendanceT.html
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
<aside>
    <h3>Categories</h3>
    <ul class="categories">
        <li class="current"><a href="{% url 'SMS:Teacher' TeacherId %}" class="m1">Details</a></li>
                      <li><a href="{% url 'SMS:TeacherTimeTable' TeacherId %}" class="m2">Time TimeTable</a></li>
                      <li><a href="{% url 'SMS:TeacherResult' TeacherId %}" class="m3">Result</a></li>
                      <li><a href="{% url 'SMS:TeacherRequest' TeacherId %}" class="m4">Request</a></li>
                      <li><a href="{% url 'SMS:TeacherAssignments' TeacherId %}" class="m5">Assignments</a></li>
                     
                      <li><a href="{% url 'SMS:TeacherPayroll' TeacherId %}" class="m7">Payroll</a></li>
                      <li><a href="{% url 'SMS:TeacherAttendance' TeacherId %}" class="m8">Attendance</a></li>
                   
    </ul>
    </aside>
    <section id="content">
    <div class="inside">
        
<h2>Student's <span>Attendance</span></h2>
<form id="contacts-form" action="#">
    <fieldset>
        <div class="field">
       
            <label>Class:</label>
            <input type="text" value=""/>
            <br>
            <label>Section:</label>
            <input type="text" value=""/>
        </div>
        <br></br>
        <table border="2" cellspacing="3" align="left">
            <tr>
                <td align="center">Registration Number
                <td align="center">Status
                
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
                   
               </tr>
               <tr>
                   <td align="center">
                   <td align="center"><font color="black"><br><select>
                    <option value="Present"> P</option>
                    <option value="Absent"> A</option>
                </select>
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
               </tr>
               <button type="button"  align = "centre">Back</button>
               <button type="button"  align = "centre">Submit</button>

     </fieldset>
</form>
      </div>
      </section>
      
      
    </div>
 {% endblock %}

SMS/templates/SMS/DateSheet.html
<title>Student's Site | Student Home</title>
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
<aside>
    <h3>Categories</h3>
    <ul class="categories">
        <li><a href= "{% url 'SMS:ViewTimeTableSudent' StudentId %}" class="m1">Time Table</a></li>
        <li><a href= "{% url 'SMS:ViewDateSheet' StudentId %}" class="m2">Date Sheet</a></li>
        <li><a href= "{% url 'SMS:ViewResult' StudentId %}" class="m3">Result</a></li>
        <li><a href= "{% url 'SMS:SendStudentRequest' StudentId %}" class="m4">Request</a></li>
        <li><a href= "{% url 'SMS:UploadStudentAssignment' StudentId %}" class="m5">Assignments</a></li>
        <li><a href= "{% url 'SMS:StudentAcademicDetail' StudentId %}" class="m6">Academic Detail</a></li>
        <li><a href= "{% url 'SMS:ViewStudentFee'  StudentId%}" class="m7">Fee</a></li>
    </ul>
    </aside>
    <section id="content">
    <div class="inside">
        <h2>Date<span>Sheet</span></h2>
        <table style="font-family: arial, sans-serif; border-collapse: collapse;width: 100%;">
            <tr>
                <th>Date</th>
                <th>Subject</th>
            </tr>
            {% for r in results %}
              {% cycle '<tr>' '' '' '' %}
                <td>{{r.Date}}</td>
                <td>{{r.CourseName}}</td>
              {% cycle '' '' '' '</tr>' %}
            {% endfor %}
          </table>
      </div>
      </section>    
      
    </div>
 {% endblock %}

SMS/templates/SMS/RequestT.html
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
<aside>
    <h3>Categories</h3>
    <ul class="categories">
        <li class="current"><a href="{% url 'SMS:Teacher' TeacherId %}" class="m1">Details</a></li>
                      <li><a href="{% url 'SMS:TeacherTimeTable' TeacherId %}" class="m2">Time TimeTable</a></li>
                      <li><a href="{% url 'SMS:TeacherResult' TeacherId %}" class="m3">Result</a></li>
                      <li><a href="{% url 'SMS:TeacherRequest' TeacherId %}" class="m4">Request</a></li>
                      <li><a href="{% url 'SMS:TeacherAssignments' TeacherId %}" class="m5">Assignments</a></li>
                     
                      <li><a href="{% url 'SMS:TeacherPayroll' TeacherId %}" class="m7">Payroll</a></li>
                      <li><a href="{% url 'SMS:TeacherAttendance' TeacherId %}" class="m8">Attendance</a></li>
                      
    </ul>
    </aside>
    <section id="content">
    <div class="inside">
        <h2>Request <span>Form</span></h2>
      <form id="contacts-form" action="#" method="POST">
        <fieldset>
          <div class="field">
            <label>Request:</label>
            <input type="text" name="Description" value="" />
            
          </div>
        </fieldset>
        
        {% csrf_token %} 
        <input class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" value="Submit" onsubmit="RequestSubmitted()"/>
      </form>
      </div>
      </section>
      
      
    </div>
 {% endblock %}

SMS/templates/SMS/Result.html
<title>Student's Site | Student Home</title>
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
  <aside>
    <h3>Categories</h3>
    <ul class="categories">
      <li><a href= "{% url 'SMS:ViewTimeTableSudent' StudentId %}" class="m1">Time Table</a></li>
        <li><a href= "{% url 'SMS:ViewDateSheet' StudentId %}" class="m2">Date Sheet</a></li>
        <li><a href= "{% url 'SMS:ViewResult' StudentId %}" class="m3">Result</a></li>
        <li><a href= "{% url 'SMS:SendStudentRequest' StudentId %}" class="m4">Request</a></li>
        <li><a href= "{% url 'SMS:UploadStudentAssignment' StudentId %}" class="m5">Assignments</a></li>
        <li><a href= "{% url 'SMS:StudentAcademicDetail' StudentId %}" class="m6">Academic Detail</a></li>
        <li><a href= "{% url 'SMS:ViewStudentFee'  StudentId%}" class="m7">Fee</a></li>
    </ul>
  </aside>
  <section id="content">
    <div class="inside">
      
<h2>Result <span></span></h2>
<form id="contacts-form" action="#">
  <fieldset>
    <div class="field">
        <label>Registration No:</label>
        <input type="text" value="{{result.RegistrationNo}}" readonly/>
    </div>
    <div class="field">
      <label>class:</label>
      <input type="text" value="{{result.ClassName}}" readonly/>
    </div>
    <div class="field">
        <label>Section:</label>
        <input type="text" value="{{result.SectionName}}" readonly/>
     </div>
    <div class="field">
        <label>Subject:</label>
            <select>

                <option value="Math">Math</option>
            </select>
    </div>
        <div class="field">
        <label>Marks:</label>
        <input type="text" value="{{result.Marks}}" readonly/>
    </div>
</fieldset>
</form>
    </div>
  </section>

</div>
{% endblock %}

SMS/templates/SMS/TimeTable.html
<title>Student's Site | Student Home</title>
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
<aside>
    <h3>Categories</h3>
    <ul class="categories">
      <li><a href= "{% url 'SMS:ViewTimeTableSudent' StudentId %}" class="m1">Time Table</a></li>
      <li><a href= "{% url 'SMS:ViewDateSheet' StudentId %}" class="m2">Date Sheet</a></li>
      <li><a href= "{% url 'SMS:ViewResult' StudentId %}" class="m3">Result</a></li>
      <li><a href= "{% url 'SMS:SendStudentRequest' StudentId %}" class="m4">Request</a></li>
      <li><a href= "{% url 'SMS:UploadStudentAssignment' StudentId %}" class="m5">Assignments</a></li>
      <li><a href= "{% url 'SMS:StudentAcademicDetail' StudentId %}" class="m6">Academic Detail</a></li>
      <li><a href= "{% url 'SMS:ViewStudentFee'  StudentId%}" class="m7">Fee</a></li>
    </ul>
    </aside>
    <section id="content">
    <div class="inside">
      <h2>Time <span>Table</span></h2>
      </div>
      </section>
      
      
    </div>
 {% endblock %}
 

SMS/templates/SMS/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Student's Site</title>
<meta charset="utf-8">

{% load static %}
<link rel="shortcut icon"  href="{% static 'SMS/SMS_Icon2.ico' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'SMS/css/reset.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'SMS/css/style.css' %}" media="all">
<script type="text/javascript" src="{% static 'SMS/js/jquery-1.4.2.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'SMS/js/cufon-yui.js' %}"></script>
<script type="text/javascript" src="{% static 'SMS/js/cufon-replace.js' %}"></script>
<script type="text/javascript" src="{% static 'SMS/js/Myriad_Pro_300.font.js' %}"></script>
<script type="text/javascript" src="{% static 'SMS/js/Myriad_Pro_400.font.js' %}"></script>
<script type="text/javascript" src="{% static 'SMS/js/script.js' %}"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script>
  function GoogleSearch(){
    query = document.getElementById("SearchInput").value
    window.location = "https://www.google.com/search?source=hp&ei=j1fNXPCxO4XYaMrIiUA&q=" + query + "&btnK=Google+Search&oq=list&gs_l=psy-ab.3..35i39j0i67l4j0i20i263j0l2j0i131j0.3019.3633..4176...3.0..0.262.1262.2-5......0....1..gws-wiz.....6.HJ-2xe5K7pk"
  }
</script>
</head>
<body id="page1">
<!-- START PAGE SOURCE -->
<div class="wrap">
  <header>
    <div class="container">
      <h1><a href="#">School Management System</a></h1>
      <nav>
        <ul>
          <li ><a href="{% url 'SMS:index' %}" class="m1">Home Page</a></li>
          <li><a href="{% url 'SMS:About'  %}" class="m2">About Us</a></li>
          <li><a href="{% url 'SMS:Articles' %}"  class="m3">Our Articles</a></li>
          <li><a href="{% url 'SMS:Contact_Us' %}" class="m4">Contact Us</a></li>
          <li class="last"><a href="{% url 'SMS:Sitemaps' %}"class="m5">Sitemap</a></li>
        </ul>
      </nav>
      <form action="#" id="search-form">
        <fieldset>
          <div class="rowElem">
            <input id = "SearchInput" type="text">
            <a onclick="GoogleSearch()" href="#">Search</a></div>
        </fieldset>
      </form>
    </div>
  </header>
  {% block content %}{% endblock %}
  
</div>
<footer>
  <div class="footerlink">
    <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
    <p class="rf">Design by <a href="http://www.templatemonster.com/">TemplateMonster</a></p>
    <div style="clear:both;"></div>
  </div>
</footer>
<script type="text/javascript"> Cufon.now(); </script>
<!-- END PAGE SOURCE -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>